simulator:
  action_space_config: v0
  agents:
  - agent_0
  default_agent_id: 0
  forward_step_size: 0.25
  scene: data/scene_datasets/habitat-test-scenes/van-gogh-room.glb
  seed: 100
  tilt_angle: 15
  turn_angle: 10
  type: Sim-v0
