simulator:
  depth_sensor:
    height: 480
    hfov: 90
    max_depth: 10
    min_depth: 0
    normalize_depth: true
    position:
    - 0
    - 1.25
    - 0
    type: HabitatSimDepthSensor
    width: 640
