habitat:
  simulator:
    action_space_config: v0
    default_agent_id: 0
    forward_step_size: 0.25
    habitat_sim_v0:
      gpu_device_id: 0
      gpu_gpu: false
    scene: data/scene_datasets/habitat-test-scenes/van-gogh-room.glb
    seed: 100
    sensor: ???
    tilt_angle: 15
    turn_angle: 10
    type: Sim-v0
