task:
  actions:
    answer:
      type: AnswerAction
    look_down:
      type: LookDownAction
    look_up:
      type: LookUpAction
    move_forward:
      type: MoveForwardAction
    stop:
      type: StopAction
    teleport:
      type: TeleportAction
    turn_left:
      type: TurnLeftAction
    turn_right:
      type: TurnRightAction
