pyrobot:
  locobot:
    actions:
    - base_actions
    - camera_actions
    base_actions:
    - go_to_relative
    - go_to_absolute
    camera_actions:
    - set_pan
    - set_tilt
    - set_pan_tilt
