defaults:
- habitat/simulator: habitat_sim_v0
- habitat/agent: agent_0
- habitat/dataset: default
- habitat/environment: default


habitat:
  seed: 100

  dataset: ???

  task:
    action_order: null
    type: ???
    action: ???
    sensor: ???
    measure: ???

  simulator: ???
  environment: ???
