defaults:
- habitat/simulator: habitat_sim_v0
- habitat/agent: agent_0
- habitat/dataset: default
- habitat/environment: default
habitat:
  dataset: ???
  environment: ???
  seed: 100
  simulator: ???
  task:
    action: ???
    action_order: null
    measure: ???
    sensor: ???
    type: ???
