defaults:
  - habitat/simulator: habitat_sim_v0
  - habitat/agent: agent_0
  - habitat/dataset: default
  - habitat/environment: default


habitat:
  seed: 100


  dataset: ???

  task:
    type: ???
    action: ???
    sensor: ???
    measure: ???
    action_order: []

  simulator: ???
  environment: ???
