habitat:
  environment:
    iterator_options:
      cycle: true
      group_by_scene: true
      max_scene_repeat_episodes: -1
      max_scene_repeat_steps: 10000
      num_episode_sample: -1
      shuffle: true
      step_repetition_range: 0.2
    max_episode_seconds: 10000000
    max_episode_steps: 1000
