rl:
  ppo:
    clip_param: 0.2
    entropy_coef: 0.01
    eps: 1.0e-05
    gamma: 0.99
    hidden_size: 512
    lr: 0.0007
    max_grad_norm: 0.5
    num_mini_batch: 16
    num_steps: 5
    ppo_epoch: 4
    reward_window_size: 50
    tau: 0.95
    use_gae: true
    use_linear_clip_decay: false
    use_linear_lr_decay: false
    value_loss_coef: 0.5
