defaults:
- habitat_baselines/trainer: ppo
- habitat_baselines/env: nav_rl
- habitat_baselines/model: baseline
habitat_baselines:
  logging:
    checkpoint_folder: data/checkpoints/ppo/pointnav/
    checkpoint_interval: 200
    interval: 25
  num_processes: 4
  simulator_gpu_id: 0
  tensorborad:
    dir: tb/pointnav
  torch_gpu_id: 0
  trainer:
    ppo:
      num_mini_batch: 2
      num_updates: 100000
  video:
    outputs: []
