checkpoint_folder: data/checkpoints
checkpoint_interval: 50
env_name: NavRLEnv
eval_ckpt_path_dir: data/checkpoints
log_file: train.log
log_interval: 10
num_processes: 16
num_updates: 10000
sensors:
- rgb_sensor
- depth_sensor
simulator_gpu_id: 0
tensorboard_dir: tb
test_episode_count: 2
torch_gpu_id: 0
trainer_name: ppo
video_dir: video_dir
video_option:
- disk
- tensorboard
