habitat_baselines:
  env: ???
  eval:
    ckpt_path_dir: data/checkpoints
    split: val
    test_episode_count: 2
    use_ckpt_config: true
  logging:
    checkpoint_folder: data/checkpoints
    checkpoint_interval: 50
    file: train.log
    interval: 10
  model: ???
  num_processes: 4
  simulator_gpu_id: 0
  tensorboard:
    dir: tb
  torch_gpu_id: 0
  trainer: ???
  video:
    dir: video_dir
    outputs:
    - disk
    - tensorboard
