habitat_baselines:
  simulator_gpu_id: 0
  torch_gpu_id: 0
  num_processes: 4

  trainer: ???
  env: ???

  logging:
    file: train.log
    interval: 10
    checkpoint_folder: data/checkpoints
    checkpoint_interval: 50

  eval:
    ckpt_path_dir: data/checkpoints
    test_episode_count: 2
    split: val
    use_ckpt_config: true

  video:
    outputs:
    - disk
    - tensorboard

    dir: video_dir

  tensorboard:
    dir: tb
